# Generated by Django 3.2.6 on 2022-03-08 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, verbose_name='Public/Private')),
                ('month', models.CharField(max_length=10, verbose_name='Month')),
                ('date', models.CharField(max_length=5, verbose_name='Date')),
                ('pin_x', models.FloatField(verbose_name='Longitude')),
                ('pin_y', models.FloatField(verbose_name='Latitude')),
                ('country', models.CharField(default='', max_length=20)),
                ('prefecture', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('emotion', models.CharField(max_length=50, verbose_name='Emotion')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Category')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.tag', verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('username', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('web', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='blog.post')),
            ],
        ),
    ]
