# Generated by Django 3.2.6 on 2022-03-08 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WantToDoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WantToDoUserPoint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WantToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('want_todo_title', models.CharField(max_length=100, verbose_name='WantToDoTitle')),
                ('want_todo_text', models.CharField(max_length=100, verbose_name='WantToDoText')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pin_x', models.FloatField()),
                ('pin_y', models.FloatField()),
                ('checked', models.BooleanField(default=None, verbose_name='is_Check')),
                ('finished', models.BooleanField(default=None, verbose_name='is_Finished')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WantToDoUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
