# Generated by Django 3.2.6 on 2022-03-08 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_title', models.CharField(max_length=100, verbose_name='NotionTitle')),
                ('notion_text', models.CharField(max_length=200, verbose_name='NotionPost')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
